#spring:
#  application:
#    name: discovery-service
#
#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#
#server:
#  port: 8761
#  forward-headers-strategy: framework

spring.config.import=optional:configserver:http://localhost:8888