spring:
  application:
    name: passenger-service

  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/passenger}
    username: ${JDBC_DATABASE_USERNAME:masd}
    password: ${JDBC_DATABASE_PASSWORD:1q2w3e!Q@W#E}

    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri=http://localhost:8080/realms/baeldung-keycloak

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true


server:
  port: 9001
