server:
  port: 8888

spring:

  profiles:
    active: mongodb

  application:
    name: config-server

  data:
    mongodb:
      database: configdb
      host: localhost
      port: 27017

  cloud:
    config:
      server:
        mongodb:
          collection: configurations